### PR TITLE
User Sign-Up

### PR DESCRIPTION
**Pull request by smeads**
@cbeck I still need to work out the mailer. I figured I'd just send this over now so we could review it.

### CODE REVIEW

**Comment by smeads** [comment]
@cbeck I think I figured it out. I ran a `rake db: rollback` added `comfirmable`to the `models/user.rb` file and then ran a `rake db:migrate`. I know get an email confirmation when I sign up a new user. I also meet the other requirements for this checkpoint. I'm going to go ahead and merge these two commits.

**Comment by smeads** [comment]
@cbeck you probably are shacking your head about me rolling back a migration that was already committed. Truth is, I am too. I did this before and you think I would have learned my lesson. Anyway, when I and `git push master` I get the following error:

``` bash
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

Yes, I know we have been here before. If you could remind me how to get my master synced back up properly that would be great.

Thanks, and sorry for the headaches.

**Comment by cbeck** [comment]
Looks like you are not in your project directory. A rollback wouldn't cause this. And no, I am not shaking my head :-)

**Comment by smeads** [comment]
How do I get back into the project directory? Would a rollback on an already migrated commit cause this? 

I've done the following but still no luck:

``` bash
[master][~/code/blocitoff]$ git push master                                                                                           rvm:ruby-2.3.0@bloc
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[master][~/code/blocitoff]$ git init                                                                                                  rvm:ruby-2.3.0@bloc
Reinitialized existing Git repository in /Users/stevenmeads/code/blocitoff/.git/
[master][~/code/blocitoff]$ git add .                                                                                                 rvm:ruby-2.3.0@bloc
[master][~/code/blocitoff]$ git commit -m "Reinitialize"                                                                              rvm:ruby-2.3.0@bloc
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
[master][~/code/blocitoff]$ git remote add origin git@github.com:smeads/blocitoff.git                                                 rvm:ruby-2.3.0@bloc
fatal: remote origin already exists.
[master][~/code/blocitoff]$ git push -f origin master                                                                                 rvm:ruby-2.3.0@bloc
Everything up-to-date
[master][~/code/blocitoff]$ git push master                                                                                           rvm:ruby-2.3.0@bloc
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by cbeck** [comment]
Looks like you are actually in your project directory. Perhaps you originally did a git init in the wrong directory?

Do this:

```
cd ../
git status
```

If that shows you anything, then you originally git init'd the directory that is the parent of your blocitoff directory, which I am assuming is not what you want. You can further confirm that by doing this:

```
ls -la
```

If you see .git as a folder and you are not in your blocitoff directory, you def have a problem. Easily solved, though.

```
sudo rm -R .git   # and enter password used to login to computer
cd blocitoff
sudo rm -R .git
git init
git add .
git commit -m "Third time's the charm"
git push origin master
```

**Comment by smeads** [comment]
I just went through the steps you suggested. I think something else is going on. If I remember right, the last time I rolled back a migration that was committed I got the same error later when I tried to `git push master`. 

Suggested steps:

``` bash
[master][~/code/blocitoff]$ cd ../                                                                                                    rvm:ruby-2.3.0@bloc
[~/code]$ git status                                                                                                                  rvm:ruby-2.3.0@bloc
fatal: Not a git repository (or any of the parent directories): .git
[~/code]$ ls -la                                                                                                                      rvm:ruby-2.3.0@bloc
total 32
drwxr-xr-x   7 stevenmeads  staff   238 Jul 22 17:03 .
drwxr-xr-x+ 58 stevenmeads  staff  1972 Jul 26 08:17 ..
-rw-r--r--@  1 stevenmeads  staff  6148 Jul 25 09:41 .DS_Store
-rw-r--r--   1 stevenmeads  staff     5 Jul  8 13:03 .ruby-gemset
-rw-r--r--   1 stevenmeads  staff     6 Jul  8 13:03 .ruby-version
drwxr-xr-x  21 stevenmeads  staff   714 Jul 19 18:26 bloccit
drwxr-xr-x  19 stevenmeads  staff   646 Jul 25 14:07 blocitoff
```

Any other suggestions? Should I still run through these steps?

``` bash
sudo rm -R .git   # and enter password used to login to computer
cd blocitoff
sudo rm -R .git
git init
git add .
git commit -m "Third time's the charm"
git push origin master
```

**Pull request merged**
